<?php

/**
 *  Implements hook_field_create_field().
 */
function mbp_defaults_field_create_field($field) {
  if ($field['type'] == 'menu_block_placement_reference') {
    $field_name = $field['field_name'];

    if (variable_get('mbp_defaults')) {
      $views = variable_get('mbp_defaults');

      $views[$field['id']] = $field_name;
      variable_set('mbp_defaults', $views);
    }
    else {
      variable_set('mbp_defaults', array($field['id'] => $field_name));
    }
  }
}

/**
 *  Implements hook_field_delete_field().
 */
function mbp_defaults_field_delete_field($field) {
  if ($field['type'] == 'menu_block_placement_reference') {
    $views = variable_get('mbp_defaults');
    unset($views[$field['id']]);
    variable_set('mbp_defaults', $views);
  }
}

function mbp_defaults_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 *  Implements hook_views_query_alter().
 */
function mbp_defaults_views_query_alter(&$view, &$query) {
  $tags = explode(', ', $view->tag);
  if (in_array('mbp_defaults', $tags)) {
    if (in_array('mbp_regions', $tags) && in_array('mbp_individual', $tags)) {
      if (isset($query->where[1]) && isset($query->where[0]) && isset($query->where[0]['conditions'][0]) && isset($query->where[0]['conditions'][1]) && isset($query->where[0]['conditions'][2])) {
        $query->group_operator = 'OR';
        $query->where[] = $query->where[1];
        $query->where[2]['conditions'][1]['value'] = '0';
        $query->where[1]['conditions'][] = $query->where[0]['conditions'][0];
        $query->where[2]['conditions'][] = $query->where[0]['conditions'][0];
        $query->where[1]['conditions'][] = $query->where[0]['conditions'][1];
        $query->where[2]['conditions'][] = $query->where[0]['conditions'][2];
        unset($query->where[0]);
      }
    }
    elseif (in_array('mbp_individual', $tags)) {
      $query->group_operator = 'OR';
      $query->where[] = $query->where[1];
      $query->where[2]['conditions'][1]['value'] = '0';
      $query->where[1]['conditions'][] = $query->where[0]['conditions'][0];
      $query->where[2]['conditions'][] = $query->where[0]['conditions'][1];
      unset($query->where[0]);
    }
    elseif (in_array('mbp_regions', $tags)) {
    }
  }
}

/**
 *  Implements hook_block_info().
 */
function mbp_defaults_block_info() {
  $regions = variable_get('menu_block_placement_regions');
  $fields = variable_get('mbp_defaults');
  $blocks = array();
  foreach ($fields as $fid => $field) {
    $field_settings = field_info_field($field);
    if ($field_settings['settings']['default_selects']['region']) {
      foreach ($regions as $key => $label) {
        $blocks['mbp-' . $fid . '-' . $key] = array(
          'info' => t('MBP-' . substr($field, 6) . '-' . $label),
          'cache' => DRUPAL_NO_CACHE,
        );
      }
    }
    else {
      $blocks['mbp-' . $fid] = array(
        'info' => t('MBP-' . substr($field, 6)),
        'cache' => DRUPAL_NO_CACHE,
      );
    }

  }
  return $blocks;
}

/**
 *  Implements hook_block_info_alter().
 */
function mbp_defaults_block_info_alter(&$blocks, $theme, $code_blocks) {
  if (isset($blocks['mbp_defaults']) && !empty($blocks['mbp_defaults'])) {
    foreach ($blocks['mbp_defaults'] as &$block) {
      if (strpos($block['delta'], '-', 5)) {
        $region = substr($block['delta'], strpos($block['delta'], '-', 5) + 1);
        $block['region'] = $region;
        $block['status'] = '1';
      }
    }
  }
}

/**
 *  Implements hook_block_view().
 */
function mbp_defaults_block_view($delta = '') {
  $fields = variable_get('mbp_defaults');
  $field_id = substr($delta, 4, strpos($delta . '-', '-', 5) - 4);
  $field_name = isset($fields[$field_id]) ? $fields[$field_id] : '';
  $region = substr($delta, strpos($delta, '-', 5) + 1);

  if ($field_name != '') {
    $block = array(
      'subject' => t(''),
      'content' => mbp_defaults_build_quicktabs($field_id, $field_name, $region),
    );
    return $block;
  }
}

/*
 * Helper Function that contains all the quicktabs settings information
 */
function mbp_defaults_build_quicktabs($field_id, $field_name, $region) {
  $field_settings = field_info_field($field_name);
  $settings = array(
    'style' => 'Zen',
    'renderer' => 'quicktabs',
    'hide_empty_tabs' => TRUE,
    'default_tab' => 0,
    'title' => 'Test Quicktabs',
    'options' => array(),
  );
  $tabs = array(
    0 => array(
      'vid' => 'mbp_' . $field_id,
      'display' => 'block',
      'args' => $field_settings['settings']['default_selects']['region'] ? $region : '',
      'title' => 'Display',
      'weight' => '-100',
      'type' => 'view',
    ),
    1 => array(
      'vid' => 'mbp_' . $field_id,
      'display' => 'block_1',
      'args' => $field_settings['settings']['default_selects']['region'] ? $region : '',
      'title' => 'Sort',
      'weight' => '-99',
      'type' => 'view',
    ),
  );
  $qt_name = $field_id . '-' . $region;

  return quicktabs_build_quicktabs($qt_name, $settings, $tabs);
}